version: '3'
services:
  netdata:
    image: "netdata/netdata"
    container_name: netdata
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/netdata/python.d/nginx.conf
      - ./httpcheck.conf:/etc/netdata/python.d/httpcheck.conf